[[Electron]]
arch = "aarch64"
git-tree-sha1 = "05248a17f4cfb96996c4d245834e0ed73d23f1e4"
os = "macos"

    [[Electron.download]]
    sha256 = "a792cd13c94bbeb2fcd562cc45cbfc5ea6eab306eace39c26271a6d812e2f7fd"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+2/Electron.v38.2.0.aarch64-apple-darwin.tar.gz"
[[Electron]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "286ac3a27065f63ca5a289ca28a8e71103ec08a6"
libc = "glibc"
os = "linux"

    [[Electron.download]]
    sha256 = "a4ca98070c943d9925962e71078b05be25eb1e38a4f8beea9fc71c1d9738b3e1"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+2/Electron.v38.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Electron]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "286ac3a27065f63ca5a289ca28a8e71103ec08a6"
libc = "musl"
os = "linux"

    [[Electron.download]]
    sha256 = "a4ca98070c943d9925962e71078b05be25eb1e38a4f8beea9fc71c1d9738b3e1"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+2/Electron.v38.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[Electron]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca50a66d279dd767345bba5e964feb56c053c38c"
libc = "glibc"
os = "linux"

    [[Electron.download]]
    sha256 = "46df6e34febc2d4cc2f4b7ddc5392581e4b9ed91093ebec818631b55368a7121"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+2/Electron.v38.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Electron]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca50a66d279dd767345bba5e964feb56c053c38c"
libc = "musl"
os = "linux"

    [[Electron.download]]
    sha256 = "46df6e34febc2d4cc2f4b7ddc5392581e4b9ed91093ebec818631b55368a7121"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+2/Electron.v38.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Electron]]
arch = "i686"
git-tree-sha1 = "f3c0a721ea442fdee61bf2ef9309d02f89e15994"
os = "windows"

    [[Electron.download]]
    sha256 = "f827167d2878b8b6d7dcb93de2035f1a4c92da4f474e251b647e2000b1a66b76"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+2/Electron.v38.2.0.i686-w64-mingw32.tar.gz"
[[Electron]]
arch = "x86_64"
git-tree-sha1 = "3e28e19118daff48ba4fb02c3486836e3cb80e3a"
os = "macos"

    [[Electron.download]]
    sha256 = "2c52b46bdfb5f726bbe2a637441bbf56496a498a06df7869d4f3e33a7d8a5029"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+2/Electron.v38.2.0.x86_64-apple-darwin.tar.gz"
[[Electron]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8364039059bf7317e88d771489ad786112af8ed"
libc = "glibc"
os = "linux"

    [[Electron.download]]
    sha256 = "4233160e08b735f036a8cde9478b513e617fe01b9279435136da60ab83743975"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+2/Electron.v38.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Electron]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8364039059bf7317e88d771489ad786112af8ed"
libc = "musl"
os = "linux"

    [[Electron.download]]
    sha256 = "4233160e08b735f036a8cde9478b513e617fe01b9279435136da60ab83743975"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+2/Electron.v38.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[Electron]]
arch = "x86_64"
git-tree-sha1 = "0b2d561a1647175f6f7818edcf4d2ac40b914913"
os = "windows"

    [[Electron.download]]
    sha256 = "a3ec98098f41408887de71a64bdc95761f9d9e51003558e141f7157f59a7b155"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+2/Electron.v38.2.0.x86_64-w64-mingw32.tar.gz"
