[[Electron]]
arch = "aarch64"
git-tree-sha1 = "05248a17f4cfb96996c4d245834e0ed73d23f1e4"
os = "macos"

    [[Electron.download]]
    sha256 = "a792cd13c94bbeb2fcd562cc45cbfc5ea6eab306eace39c26271a6d812e2f7fd"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+1/Electron.v38.2.0.aarch64-apple-darwin.tar.gz"
[[Electron]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8adeb6d1fd745f35a8a98638d0cb099763685435"
libc = "glibc"
os = "linux"

    [[Electron.download]]
    sha256 = "d80552ab66a979fc6042312c138fda98fe49c8e108258de89cc2af2eaf3ce3d1"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+1/Electron.v38.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Electron]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8adeb6d1fd745f35a8a98638d0cb099763685435"
libc = "musl"
os = "linux"

    [[Electron.download]]
    sha256 = "d80552ab66a979fc6042312c138fda98fe49c8e108258de89cc2af2eaf3ce3d1"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+1/Electron.v38.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[Electron]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b833973735fedfcf0123e1639c14e458c3d06887"
libc = "glibc"
os = "linux"

    [[Electron.download]]
    sha256 = "537b364b1b67822238f19325211b62e8c78e44571fc718099a4b3a019291110e"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+1/Electron.v38.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Electron]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b833973735fedfcf0123e1639c14e458c3d06887"
libc = "musl"
os = "linux"

    [[Electron.download]]
    sha256 = "537b364b1b67822238f19325211b62e8c78e44571fc718099a4b3a019291110e"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+1/Electron.v38.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Electron]]
arch = "i686"
git-tree-sha1 = "6aa3cfb356c286bb99bbe05575b80d8d4b3a7bcc"
os = "windows"

    [[Electron.download]]
    sha256 = "e27dd85ca232d7bbc9775982d3eae9107999ba64bcd24d4b6758d9752e99c66b"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+1/Electron.v38.2.0.i686-w64-mingw32.tar.gz"
[[Electron]]
arch = "x86_64"
git-tree-sha1 = "3e28e19118daff48ba4fb02c3486836e3cb80e3a"
os = "macos"

    [[Electron.download]]
    sha256 = "2c52b46bdfb5f726bbe2a637441bbf56496a498a06df7869d4f3e33a7d8a5029"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+1/Electron.v38.2.0.x86_64-apple-darwin.tar.gz"
[[Electron]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6311413c5021c9a6d39df15e79b7d0311600f430"
libc = "glibc"
os = "linux"

    [[Electron.download]]
    sha256 = "7348081859f6bc654cdb83d7b62511372867c958f9c454d05f1c14bc10df50f2"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+1/Electron.v38.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Electron]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6311413c5021c9a6d39df15e79b7d0311600f430"
libc = "musl"
os = "linux"

    [[Electron.download]]
    sha256 = "7348081859f6bc654cdb83d7b62511372867c958f9c454d05f1c14bc10df50f2"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+1/Electron.v38.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[Electron]]
arch = "x86_64"
git-tree-sha1 = "2b7c56c0ff3a98cdc1ba0b9db26a7f331f0ae01f"
os = "windows"

    [[Electron.download]]
    sha256 = "9de830a7c923f3351b6db09de95dbc871f1137a3ea7dfae8da3fb334010e03fa"
    url = "https://github.com/JuliaBinaryWrappers/Electron_jll.jl/releases/download/Electron-v38.2.0+1/Electron.v38.2.0.x86_64-w64-mingw32.tar.gz"
