# Autogenerated wrapper script for Electron_jll for armv7l-linux-musleabihf-cxx11
export electron

using Xorg_libX11_jll
using Xorg_libXext_jll
using Xorg_libXfixes_jll
using Xorg_libXdamage_jll
using Xorg_libXrandr_jll
using Xorg_libXcomposite_jll
using Xorg_libxcb_jll
using GTK3_jll
using Glib_jll
using Pango_jll
using Cairo_jll
using at_spi2_atk_jll
using at_spi2_core_jll
using ATK_jll
using alsa_jll
using Dbus_jll
using Expat_jll
using xkbcommon_jll
JLLWrappers.@generate_wrapper_header("Electron")
JLLWrappers.@declare_executable_product(electron)
function __init__()
    JLLWrappers.@generate_init_header(Xorg_libX11_jll, Xorg_libXext_jll, Xorg_libXfixes_jll, Xorg_libXdamage_jll, Xorg_libXrandr_jll, Xorg_libXcomposite_jll, Xorg_libxcb_jll, GTK3_jll, Glib_jll, Pango_jll, Cairo_jll, at_spi2_atk_jll, at_spi2_core_jll, ATK_jll, alsa_jll, Dbus_jll, Expat_jll, xkbcommon_jll)
    JLLWrappers.@init_executable_product(
        electron,
        "bin/electron",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
