# Autogenerated wrapper script for Electron_jll for i686-w64-mingw32
export electron

JLLWrappers.@generate_wrapper_header("Electron")
JLLWrappers.@declare_executable_product(electron)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        electron,
        "bin\\electron.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
