# Autogenerated wrapper script for Electron_jll for x86_64-apple-darwin
export electron

JLLWrappers.@generate_wrapper_header("Electron")
JLLWrappers.@declare_executable_product(electron)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        electron,
        "bin/electron",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
